apiVersion: v1
kind: Pod
metadata:
  name: curl-util
  namespace: argocd
spec:
  containers:
  - name: curl-util
    image: busybox:1.31 
    command:
    - sh
    - -c
    - while true; do sleep 1; done
